image: node:latest

stages:
  - build
  - unitTest
  - integerationTest
  - release

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_unit:
  stage: unitTest
  script:
    - npm install --save-dev jest
    - npm test

testing_integeration:
  stage: integerationTest
  script:
    - npm install --save-dev jest
    - npm test

release:
  image: docker:19.03.1
  stage: release
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t jalas-front .
    - docker push jalas-front
  only:
    - master
